[versions]
agp = "8.0.2"
datastore = "1.0.0"

[libraries]
lifecycle-runtimektx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.6.1" }
corektx = "androidx.core:core-ktx:1.10.1"

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.library", version.ref = "agp" }
test = { id = "com.android.test", version.ref = "agp" }