[versions]
compose-bom = "2023.06.01"

[libraries]
activity = "androidx.activity:activity-compose:1.7.2"
bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { module = "androidx.compose.ui:ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
material3-core = { module = "androidx.compose.material3:material3" }
